// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_jazz3987.Models;

namespace Mission06_jazz3987.Migrations
{
    [DbContext(typeof(MovieInfoContext))]
    [Migration("20230214004413_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_jazz3987.Models.MovieForm", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("MovieForms");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Anime",
                            Director = "Makoto Shinkai",
                            Edited = "",
                            LentTo = "",
                            Notes = "",
                            Rating = "PG-13",
                            Title = "Kimi no na wa",
                            Year = 2016
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Anime",
                            Director = "Makoto Shinkai",
                            Edited = "No",
                            LentTo = "",
                            Notes = "",
                            Rating = "PG-13",
                            Title = "Tenki no Ko",
                            Year = 2019
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Comedy/Drama",
                            Director = "Daniel Kwan",
                            Edited = "",
                            LentTo = "Jacob",
                            Notes = "Very trippy",
                            Rating = "R",
                            Title = "Everything Everywhere All at Once",
                            Year = 2022
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
