// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_jazz3987.Models;

namespace Mission06_jazz3987.Migrations
{
    [DbContext(typeof(MovieInfoContext))]
    partial class MovieInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_jazz3987.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Anime"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Comedy/Drama"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Action/Adventure"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Drama"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Family"
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Horror/Suspense"
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "Miscellaneous"
                        },
                        new
                        {
                            CategoryID = 9,
                            CategoryName = "Television"
                        },
                        new
                        {
                            CategoryID = 10,
                            CategoryName = "VHS"
                        });
                });

            modelBuilder.Entity("Mission06_jazz3987.Models.MovieForm", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.HasIndex("CategoryID");

                    b.ToTable("MovieForms");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CategoryID = 1,
                            Director = "Makoto Shinkai",
                            Edited = "",
                            LentTo = "",
                            Notes = "",
                            Rating = "PG-13",
                            Title = "Kimi no na wa",
                            Year = 2016
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryID = 1,
                            Director = "Makoto Shinkai",
                            Edited = "No",
                            LentTo = "",
                            Notes = "",
                            Rating = "PG-13",
                            Title = "Tenki no Ko",
                            Year = 2019
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryID = 2,
                            Director = "Daniel Kwan",
                            Edited = "",
                            LentTo = "Jacob",
                            Notes = "Very trippy",
                            Rating = "R",
                            Title = "Everything Everywhere All at Once",
                            Year = 2022
                        });
                });

            modelBuilder.Entity("Mission06_jazz3987.Models.MovieForm", b =>
                {
                    b.HasOne("Mission06_jazz3987.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
